# Generated by Django 4.2.1 on 2023-05-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_title_id', models.IntegerField(null=True)),
                ('original_title', models.CharField(max_length=100, null=True)),
                ('year', models.IntegerField(null=True)),
                ('date_published', models.DateField(null=True)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('duration', models.IntegerField(null=True)),
                ('language', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'movies_table',
            },
        ),
    ]
